config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  resources :users do
  end

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  resources :cuisines do
  end

  resources :orders do
  end

  #管理者
  namespace :admin do
    resources :users do
    end

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create", as: "administrator_login"
    delete "/logout",  to: "sessions#destroy"

    resources :cuisines, format: :html do
    end

    resources :orders do
    end

    resources :topics do
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :session
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
# == Schema Information
#
# Table name: cuisines
#
#  id         :bigint           not null, primary key
#  name       :string(255)
#  price      :integer
#  text       :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cuisine < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :text, presence: true
  validates :image, presence: true

  # has_many :cuisines_orders
  has_and_belongs_to_many :orders
  mount_uploader :image, ImageUploader
end

app/models/cuisines_order.rb
# == Schema Information
#
# Table name: cuisines_orders
#
#  id         :bigint           not null, primary key
#  order_id   :bigint           not null
#  cuisine_id :bigint           not null
#
# Indexes
#
#  index_cuisines_orders_on_cuisine_id  (cuisine_id)
#  index_cuisines_orders_on_order_id    (order_id)
#
# Foreign Keys
#
#  fk_rails_...  (cuisine_id => cuisines.id)
#  fk_rails_...  (order_id => orders.id)
#
class CuisinesOrder < ApplicationRecord
  validates :orders_id, presence: true
  validates :cuisine_id, presence: true

  has_many :cuisines
  has_many :users
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :bigint           not null, primary key
#  payment_id    :integer
#  user_id       :bigint           not null
#  quantity      :integer
#  cuisine_name  :string(255)
#  cuisine_price :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_orders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Order < ApplicationRecord
  # validates :cuisine_id, presence: true
  validates :quantity, presence: true
  validates :cuisine_name, presence: true, length: { maximum: 200 }
  validates :cuisine_price, presence: true

  # has_many :cuisines_orders
  # has_many :cuisines, through: :cuisines_orders
  has_and_belongs_to_many :cuisines
  belongs_to :user
end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :bigint           not null, primary key
#  pay        :integer
#  settled    :boolean          default(FALSE), not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Payment < ApplicationRecord
  validates :pay, presence: true
  validates :settled, presence: true
  validates :user_id, presence: true
  
  has_many :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  role            :integer          default(1), not null
#  admin           :boolean          default(FALSE), not null
#
class User < ApplicationRecord
  validates :name, presence: true, length: { minimu: 5, maximum: 50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def payments
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @cuisines = Cuisine.all
    @orders = Order.new
  end

  def create

    # Cuisine tableのレコードをid で取得するし変数に代入する。
    cuisine = Cuisine.find(cuisine_id)
    # cuisine = Cuisine.find_by(id: cuisine_id) # これなら存在しないID指定してもエラーにはならない。

    # Cusine.find で見つからない場合は ActiveRecord::RecordNotFound という例外が発生して処理終了する。
    # rails の場合、AcitveReocrd::RecordNotFound という例外が発生した場合、「404（Not Found）ページを表示する」という挙動をするのがデフォ。

    # 商品の内容が null だったらredirect させる。
    # if cuisine == 'null'
    # if cuisine.nil? || cuisine.blank?
    # unless cuisine.present?
    #   redirect_to new_order_path, danger: 'オーダーに失敗しました'
    #   return
    # end

    # # Orderモデルのインスタンスを生成する。
    # order = Order.new(
    #   user_id: current_user.id,
    #   cuisine_id: cuisine_id,
    #   quantity: 1,
    #   cuisine_name: cuisine.name,
    #   cuisine_price: cuisine.price
    # )

    # 「誰からの注文」を実装上表現してOrderのインスタンスを生成する。
    order = current_user.orders.build(
      # cuisine_id: cuisine_id,
      quantity: 1,
      cuisine_name: cuisine.name,
      cuisine_price: cuisine.price
    )

    # #  Orderモデルのuser_id カラムにcurrent_user.id を入れる。
    # order.user_id = current_user.id

    # #  Orderモデルのcuisine_id カラムにparams で取得した商品id を入れる。
    # order.cuisine_id = cuisine_id

    # #  Orderモデルのquantity カラムに数量を代入する。
    # order.quantity = 1

    # # Orderモデルのcuisine_name カラムに商品の名前を代入する。
    # order.cuisine_name  = cuisine.name

    # # Orderモデルのcuisine_price カラムに商品の値段を代入する。
    # order.cuisine_price  = cuisine.price

    # order をsave させる。
    if order.save
      # save できたら、リダイレクトさせる。
      redirect_to new_order_path, success: '商品をオーダーしました'
    else
      redirect_to new_order_path, danger: 'オーダーに失敗しました'
    end
  end

  private

  def cuisine_id
    params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  private

  def should_show_footer?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: "登録が完了しました"
    else
      flash.now[:danger] = "登録失敗です"
      render :new
    end
  end

  def index
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <header>
      <div class="link_wrapper">
        <div class="main_logo_group">
          <a href="/admin/orders">
            <%= image_tag "usi.png", class: "main_logo_img" %>
            <p>Meat Prak</p>
          </a>
          <p>Cherish deliciousness</p>
        </div>
      </div>
      <% if logged_in? %>
        <div id="topics_link_group">
          <div>
            <%= link_to "Order", admin_orders_path %>
          </div>

          <div>
            <% if current_user && current_user.admin %>
              <%= link_to "Admin registration","/admin/users/new" %>
            <% end %>
          </div>

          <div>
            <%= link_to "Users", "/admin/users" %>
          </div>

          <div>
            <%= link_to "Cuisines", "/admin/cuisines" %>
          </div>

          <div>
            <%= link_to "Sign out", "/admin/logout", method: :delete %>
          </div>
        </div>
      <% end %>
    </header>

    <div class="main-content">
      <%= yield %>

      <script>
        $(function(){
          $(".alert").fadeOut(5000);
        });
      </script>
    </div>

    <footer>
      <p>(C) 2021 Self Order System.</p>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <%= yield %>
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <header>
      <div class="link_wrapper">
        <div class="main_logo_group">
          <a href="/">
            <%= image_tag "usi.png", class: "main_logo_img" %>
            <p>Meat Park</p>
          </a>
          <p>Cherish deliciousness</p>
        </div>

        <div class="link_group">
          <% if logged_in? %>
            <%= link_to "Sign out", "/logout", method: :delete, class: "front_common_link" %>
            <%= link_to "Order","/orders/new" %>
          <% else %>
            <%= link_to "Sign up","/users/new" %>
            <%= link_to "Sign in", "/login" %>
          <% end %>
        </div>
      </div>
    </header>

    <div class="main-content">
      <%= yield %>

      <script>
        $(function(){
          $(".alert").fadeOut(5000);
        });
      </script>
    </div>

    <% if should_show_footer? %>
      <footer>
        <p>(C) 2021 Self Order System.</p>
      </footer>
    <% end %>
  </body>
</html>

app/views/pages/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.3/tiny-slider.css">

<%# app/assets 配下においたものはそれ専用の海藻に配置されるのでこのアクセスの仕方は出来ない。 %>
<%# <link rel="stylesheet" href="css/style.css"> %>
<%# <link rel="stylesheet" href="css/ress.css"> %>
<%# <link rel="stylesheet" href="css/slick-theme.css"> %>
<%# <link rel="stylesheet" href="css/slick.css"> %>
<ul class="slider">
  <li><img class="photo" src="/assets/top-img.jpg" alt=""></li>
  <li><img class="photo" src="/assets/top1.png" alt=""></li>
  <li><img class="photo" src="/assets/top2.jpg" alt=""></li>
  <li><img class="photo" src="/assets/top3.jpg" alt=""></li>
</ul>

<script>
var slider = tns({
  container: '.slider',
  items: 1,
  "speed": 1000,
  "autoplay": true,
  "autoplayHoverPause": false,
  "autoplayTimeout": 2200,
  "autoHeight": true,
  "autoplayText": [
    "▶",
    "❚❚"
  ],
  "swipeAngle": false
});
</script>






<%# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> %>
<%# <script src="js/slick.js"></script> %>

<script>
/**
$(document).ready(function(){
  $('.slider').slick({

  });
});
*/
// document.addEventListener('DOMContentLoaded', function () {
//   // document.querySelector('.slider').children
//   console.log('loaded!')

//   $('.slider').slick({
//     arrows: true,
//     infinite: false,
//     dots: true,
//   });
// })
// </script>